# Generated by Django 2.0.2 on 2018-08-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_food_calories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealfood',
            name='food',
        ),
        migrations.RemoveField(
            model_name='mealfood',
            name='meal',
        ),
        migrations.AddField(
            model_name='meal',
            name='foods',
            field=models.ManyToManyField(to='api.Food'),
        ),
        migrations.DeleteModel(
            name='MealFood',
        ),
    ]
