# Generated by Django 2.0.2 on 2018-08-29 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180827_0325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ('id',)},
        ),
    ]
